#!/usr/bin/env python3
"""Ingredient lexicons for the languages `multilingual.py` doesn't cover.

`multilingual.py` already carries hand-built Chinese and Russian maps, which
between them cover ~95% of the corpus by recipe count. The remaining ~5% spans
twelve languages, and without lexicons every one of those recipes contributes
nothing to the graph -- they'd parse cleanly and then match zero vocabulary,
which is worse than a crash because it's silent.

Each map is surface form -> canonical vocabulary name (underscore form, as it
appears in canonical_vocabulary.parquet). Keys were seeded from the empirical
frequency ranking in data/derived/lang_terms/<lang>.json, so the entries are
ordered by how much corpus they actually buy rather than by intuition.

Unmapped keys are reported by `validate()` -- a typo'd target silently drops an
ingredient, so this is checked at import time by the normalizer's audit.
"""
from __future__ import annotations

# ---------------------------------------------------------------- Turkish
TR = {
    "tuz": "salt", "sıvı yağ": "vegetable_oil", "un": "flour",
    "yumurta": "egg", "süt": "milk", "şeker": "sugar", "toz şeker": "sugar",
    "kabartma tozu": "baking_powder", "vanilya": "vanilla",
    "vanilin": "vanilla", "su": "water", "karabiber": "black_pepper",
    "sarımsak": "garlic", "sarimsak": "garlic", "tereyağı": "butter",
    "tereyağ": "butter", "tereyagi": "butter", "zeytinyağı": "olive_oil",
    "yoğurt": "yogurt", "yogurt": "yogurt", "yumurta sarısı": "egg_yolk",
    "yumurta akı": "egg_white", "pul biber": "chili_pepper",
    "pulbiber": "chili_pepper", "pudra şekeri": "sugar",
    "maydanoz": "parsley", "kakao": "cocoa_powder", "nişasta": "cornstarch",
    "soğan": "onion", "kuru soğan": "onion", "domates": "tomato",
    "domates salçası": "tomato", "salça": "tomato",
    "biber salçası": "chili_paste", "kekik": "thyme", "kimyon": "cumin",
    "limon suyu": "lemon", "limon": "lemon", "patates": "potato",
    "hindistan cevizi": "coconut", "irmik": "semolina", "havuç": "carrot",
    "tarçın": "cinnamon", "yeşil biber": "bell_pepper", "sirke": "vinegar",
    "kaşar peyniri": "cheese", "kaşar": "cheese", "peynir": "cheese",
    "beyaz peynir": "feta_cheese", "lor peyniri": "ricotta_cheese",
    "susam": "sesame_seed", "kırmızı toz biber": "paprika",
    "toz kırmızı biber": "paprika", "kırmızı biber": "red_pepper",
    "kıyma": "beef", "kıyma eti": "beef", "nane": "mint",
    "kuru nane": "mint", "krema": "cream", "margarin": "margarine",
    "dereotu": "dill", "yufka": "phyllo_dough", "ceviz": "walnut",
    "kapya biber": "red_pepper", "galeta unu": "bread_crumbs",
    "pirinç": "rice", "kuru maya": "yeast", "instant maya": "yeast",
    "maya": "yeast", "krem şanti": "cream", "çörek otu": "nigella_seed",
    "bitter çikolata": "chocolate", "çikolata": "chocolate",
    "karbonat": "baking_soda", "patlıcan": "eggplant", "biber": "black_pepper",
    "tavuk": "chicken", "tavuk göğsü": "chicken", "et": "beef",
    "dana eti": "beef", "kuzu eti": "lamb", "balık": "fish",
    "mercimek": "lentil", "kırmızı mercimek": "lentil",
    "nohut": "chickpea", "fasulye": "bean", "kuru fasulye": "white_bean",
    "bulgur": "bulgur", "makarna": "pasta", "şehriye": "vermicelli",
    "kabak": "zucchini", "salatalık": "cucumber", "marul": "lettuce",
    "ıspanak": "spinach", "lahana": "cabbage", "pırasa": "leek",
    "mantar": "mushroom", "bezelye": "pea", "mısır": "corn",
    "zeytin": "olive", "elma": "apple", "muz": "banana", "portakal": "orange",
    "çilek": "strawberry", "üzüm": "grape", "kayısı": "apricot",
    "vişne": "cherry", "kiraz": "cherry", "şeftali": "peach",
    "armut": "pear", "incir": "fig", "hurma": "date", "fındık": "hazelnut",
    "badem": "almond", "antep fıstığı": "pistachio", "ay çekirdeği": "sunflower_seed",
    "bal": "honey", "pekmez": "molasses", "tahin": "tahini",
    "reçel": "jam", "ekmek": "bread", "maydonoz": "parsley",
    "sıvı yağı": "vegetable_oil", "ayçiçek yağı": "sunflower_oil",
    "mısır yağı": "corn_oil", "nar ekşisi": "pomegranate_molasses",
    "yenibahar": "allspice", "defne yaprağı": "bay_leaf",
    "zencefil": "ginger", "muskat": "nutmeg", "karanfil": "clove",
    "vanilya şekeri": "vanilla", "labne": "cream_cheese",
    "süzme yoğurt": "yogurt", "ayran": "yogurt", "kaymak": "clotted_cream",
    "sucuk": "sausage", "pastırma": "pastrami", "salam": "salami",
    "sosis": "sausage", "jambon": "ham", "ton balığı": "tuna",
    "hamsi": "anchovy", "karides": "shrimp", "midye": "mussel",
    "roka": "arugula", "tere": "watercress", "turp": "radish",
    "kereviz": "celery", "brokoli": "broccoli", "karnabahar": "cauliflower",
    "enginar": "artichoke", "bamya": "okra", "taze soğan": "scallion",
    "yeşil soğan": "scallion", "kuru üzüm": "raisin",
    "kuru kayısı": "apricot", "vanilya özütü": "vanilla",
    "portakal suyu": "orange", "limon kabuğu": "lemon",
    "portakal kabuğu": "orange", "soda": "club_soda",
    "sıcak su": "water", "ılık su": "water", "ılık süt": "milk",
    "damla sakızı": "mastic", "damla çikolata": "chocolate",
    "kaju": "cashew", "yer fıstığı": "peanut", "susam yağı": "sesame_oil",
    "soya sosu": "soy_sauce", "ketçap": "ketchup", "mayonez": "mayonnaise",
    "hardal": "mustard", "sumak": "sumac", "pul": "chili_pepper",
    "kişniş": "coriander", "safran": "saffron", "haşhaş": "poppy_seed",
    "keten tohumu": "flaxseed", "yulaf": "oat", "arpa": "barley",
    "buğday": "wheat", "kepek": "bran", "nişasta unu": "cornstarch",
    "puf böreği": "pastry", "kuru dereotu": "dill",
}

# ---------------------------------------------------------------- Spanish
ES = {
    "sal": "salt", "ajo": "garlic", "ajos": "garlic", "dientes de ajo": "garlic",
    "pimienta": "black_pepper", "pimienta negra": "black_pepper",
    "pimienta negra molida": "black_pepper", "azúcar": "sugar",
    "azucar": "sugar", "cebolla": "onion", "cebollas": "onion",
    "cebolla morada": "red_onion", "huevo": "egg", "huevos": "egg",
    "mantequilla": "butter", "manteca": "lard", "harina": "flour",
    "harina de trigo": "flour", "harina trigo": "flour", "aceite": "oil",
    "aceite de oliva": "olive_oil", "aceite oliva": "olive_oil",
    "aceite vegetal": "vegetable_oil", "aceite de girasol": "sunflower_oil",
    "perejil": "parsley", "agua": "water", "laurel": "bay_leaf",
    "hoja de laurel": "bay_leaf", "leche": "milk", "orégano": "oregano",
    "zanahoria": "carrot", "zanahorias": "carrot", "queso": "cheese",
    "queso parmesano": "parmesan_cheese", "queso crema": "cream_cheese",
    "queso rallado": "cheese", "cilantro": "coriander", "comino": "cumin",
    "limón": "lemon", "limon": "lemon", "jugo de limón": "lemon",
    "jugo limón": "lemon", "nuez moscada": "nutmeg", "arroz": "rice",
    "tomillo": "thyme", "canela": "cinnamon", "pimiento rojo": "red_pepper",
    "pimiento verde": "bell_pepper", "pimiento": "black_pepper",
    "tomate": "tomato", "tomates": "tomato", "patata": "potato",
    "patatas": "potato", "papa": "potato", "papas": "potato",
    "esencia de vainilla": "vanilla", "esencia vainilla": "vanilla",
    "vainilla": "vanilla", "pan": "bread", "pan rallado": "bread_crumbs",
    "champiñones": "mushroom", "polvo de hornear": "baking_powder",
    "polvo hornear": "baking_powder", "levadura": "yeast",
    "bicarbonato": "baking_soda", "mayonesa": "mayonnaise",
    "crema de leche": "cream", "crema leche": "cream", "nata": "cream",
    "lechuga": "lettuce", "leche condensada": "condensed_milk",
    "leche evaporada": "evaporated_milk", "vinagre": "vinegar",
    "apio": "celery", "vino blanco": "white_wine", "vino tinto": "red_wine",
    "albahaca": "basil", "pollo": "chicken", "pechuga de pollo": "chicken",
    "carne": "beef", "carne molida": "beef", "carne picada": "beef",
    "ternera": "beef", "cerdo": "pork", "cordero": "lamb",
    "pescado": "fish", "atún": "tuna", "camarones": "shrimp",
    "gambas": "shrimp", "chorizo": "chorizo", "jamón": "ham",
    "tocino": "bacon", "panceta": "bacon", "salchicha": "sausage",
    "frijoles": "bean", "judías": "bean", "garbanzos": "chickpea",
    "lentejas": "lentil", "guisantes": "pea", "maíz": "corn",
    "choclo": "corn", "calabacín": "zucchini", "calabaza": "pumpkin",
    "berenjena": "eggplant", "espinaca": "spinach", "espinacas": "spinach",
    "brócoli": "broccoli", "coliflor": "cauliflower", "repollo": "cabbage",
    "pepino": "cucumber", "aguacate": "avocado", "palta": "avocado",
    "aceitunas": "olive", "alcaparras": "caper", "puerro": "leek",
    "cebolleta": "scallion", "cebollín": "scallion", "chile": "chili_pepper",
    "ají": "chili_pepper", "jalapeño": "jalapeno", "pimentón": "paprika",
    "paprika": "paprika", "curry": "curry_powder", "azafrán": "saffron",
    "jengibre": "ginger", "clavo de olor": "clove", "romero": "rosemary",
    "menta": "mint", "hierbabuena": "mint", "eneldo": "dill",
    "manzana": "apple", "plátano": "banana", "banana": "banana",
    "naranja": "orange", "jugo de naranja": "orange",
    "fresa": "strawberry", "fresas": "strawberry", "frutilla": "strawberry",
    "piña": "pineapple", "mango": "mango", "durazno": "peach",
    "melocotón": "peach", "pera": "pear", "uvas": "grape",
    "pasas": "raisin", "coco": "coconut", "nuez": "walnut",
    "nueces": "walnut", "almendras": "almond", "maní": "peanut",
    "cacahuate": "peanut", "miel": "honey", "chocolate": "chocolate",
    "cacao": "cocoa_powder", "chocolate amargo": "chocolate",
    "azúcar morena": "brown_sugar", "azúcar glass": "sugar",
    "maicena": "cornstarch", "fécula de maíz": "cornstarch",
    "caldo de pollo": "chicken_broth", "caldo de carne": "broth",
    "caldo de verduras": "vegetable_stock", "salsa de soja": "soy_sauce",
    "salsa de tomate": "tomato", "mostaza": "mustard",
    "yogur": "yogurt", "crema agria": "sour_cream", "ricotta": "ricotta_cheese",
    "mozzarella": "mozzarella_cheese", "gelatina": "gelatin",
    "fideos": "noodle", "pasta": "pasta", "espagueti": "pasta",
    "tortillas": "tortilla", "avena": "oat", "sémola": "semolina",
    "ron": "rum", "brandy": "brandy", "cerveza": "beer",
}

# ------------------------------------------------------------- Vietnamese
VI = {
    "muối": "salt", "dầu ăn": "vegetable_oil", "đường": "sugar",
    "đường trắng": "sugar", "đường cát": "sugar", "đường bột": "sugar",
    "tiêu": "black_pepper", "hạt tiêu": "black_pepper", "trứng": "egg",
    "trứng gà": "egg", "lòng đỏ trứng": "egg_yolk", "lòng trắng trứng": "egg_white",
    "hạt nêm": "broth", "nước mắm": "fish_sauce", "nước tương": "soy_sauce",
    "tỏi": "garlic", "tỏi băm": "garlic", "hành": "onion",
    "hành tây": "onion", "hành tím": "shallot", "hành lá": "scallion",
    "bột mì": "flour", "nước": "water", "ớt": "chili_pepper",
    "ớt bột": "chili_powder", "ớt chuông": "bell_pepper", "ớt sừng": "chili_pepper",
    "bột ngọt": "msg", "mì chính": "msg", "cà rốt": "carrot",
    "chanh": "lime", "nước cốt chanh": "lime", "dầu mè": "sesame_oil",
    "giấm": "vinegar", "sữa tươi": "milk", "sữa đặc": "condensed_milk",
    "mật ong": "honey", "dầu olive": "olive_oil", "dầu oliu": "olive_oil",
    "tôm": "shrimp", "tôm tươi": "shrimp", "rượu trắng": "rice_wine",
    "dầu hào": "oyster_sauce", "cà chua": "tomato", "gừng": "ginger",
    "nước cốt dừa": "coconut_milk", "thịt bò": "beef", "thịt heo": "pork",
    "thịt lợn": "pork", "thịt gà": "chicken", "thịt ba chỉ": "pork",
    "sả": "lemongrass", "ngò rí": "coriander", "ngò": "coriander",
    "rau mùi": "coriander", "tương ớt": "chili_sauce", "phô mai": "cheese",
    "bột bắp": "cornstarch", "bột năng": "tapioca",
    "bơ": "butter", "bơ lạt": "butter", "mè trắng": "sesame_seed",
    "mè": "sesame_seed", "đậu phộng": "peanut", "lạc": "peanut",
    "dưa leo": "cucumber", "dưa chuột": "cucumber", "vani": "vanilla",
    "tinh chất vani": "vanilla", "khoai tây": "potato",
    "khoai lang": "sweet_potato", "chuối": "banana",
    "bột nở": "baking_powder", "muối nở": "baking_soda",
    "kem whipping": "cream", "kem tươi": "cream",
    "nấm": "mushroom", "nấm hương": "shiitake_mushroom",
    "nấm rơm": "straw_mushroom", "đậu hũ": "tofu", "đậu phụ": "tofu",
    "cá": "fish", "cá hồi": "salmon", "cá basa": "catfish",
    "mực": "squid", "cua": "crab", "nghêu": "clam",
    "bún": "vermicelli", "phở": "rice_noodle", "bánh phở": "rice_noodle",
    "mì": "noodle", "miến": "glass_noodle", "gạo": "rice",
    "gạo nếp": "glutinous_rice", "bột gạo": "rice",
    "bột nếp": "glutinous_rice_flour", "dừa": "coconut",
    "hành phi": "shallot", "rau muống": "water_spinach",
    "cải thảo": "napa_cabbage", "cải ngọt": "bok_choy", "bắp cải": "cabbage",
    "giá đỗ": "bean_sprout", "giá": "bean_sprout", "rau răm": "vietnamese_coriander",
    "húng quế": "basil", "húng lủi": "mint", "rau thơm": "herb",
    "đậu xanh": "mung_bean", "đậu đỏ": "red_bean", "hạt sen": "lotus_seed",
    "bí đỏ": "pumpkin", "bí xanh": "winter_melon", "su hào": "kohlrabi",
    "măng": "bamboo_shoot", "ngô": "corn", "bắp": "corn",
    "xoài": "mango", "dứa": "pineapple", "thơm": "pineapple",
    "cam": "orange", "táo": "apple", "dâu tây": "strawberry",
    "bột cà ri": "curry_powder", "ngũ vị hương": "five_spice_powder",
    "quế": "cinnamon", "hoa hồi": "star_anise", "đinh hương": "clove",
    "lá chanh": "kaffir_lime_leaf", "riềng": "galangal", "nghệ": "turmeric",
    "mắm tôm": "shrimp_paste", "tương đen": "hoisin_sauce",
    "sữa chua": "yogurt", "socola": "chocolate", "bột cacao": "cocoa_powder",
    "men": "yeast", "gelatin": "gelatin", "đường nâu": "brown_sugar",
    "đường thốt nốt": "palm_sugar", "nước dừa": "coconut_water",
    "trà xanh": "green_tea", "cà phê": "coffee", "rượu vang": "wine",
}

# -------------------------------------------------------------- Indonesian
ID = {
    "bawang putih": "garlic", "garam": "salt", "bawang merah": "shallot",
    "air": "water", "kecap manis": "sweet_soy_sauce", "kecap asin": "soy_sauce",
    "kecap": "soy_sauce", "gula": "sugar", "gula pasir": "sugar",
    "gula merah": "palm_sugar", "gula jawa": "palm_sugar",
    "minyak goreng": "vegetable_oil", "minyak": "oil",
    "minyak wijen": "sesame_oil", "kemiri": "candlenut", "tomat": "tomato",
    "daun salam": "bay_leaf", "daun jeruk": "kaffir_lime_leaf",
    "daun bawang": "scallion", "ketumbar": "coriander",
    "ketumbar bubuk": "coriander", "telur": "egg", "telur ayam": "egg",
    "merica": "black_pepper", "merica bubuk": "black_pepper",
    "lada": "black_pepper", "lada bubuk": "black_pepper",
    "cabe rawit": "chili_pepper", "cabai rawit": "chili_pepper",
    "cabe merah": "chili_pepper", "cabai merah": "chili_pepper",
    "cabe": "chili_pepper", "cabai": "chili_pepper", "jahe": "ginger",
    "bawang bombay": "onion", "kunyit": "turmeric",
    "penyedap rasa": "msg", "penyedap": "msg", "kaldu bubuk": "broth",
    "saus tiram": "oyster_sauce", "saos tiram": "oyster_sauce",
    "tepung terigu": "flour", "tepung maizena": "cornstarch",
    "tepung beras": "rice", "tepung tapioka": "tapioca",
    "lengkuas": "galangal", "wortel": "carrot", "jeruk nipis": "lime",
    "serai": "lemongrass", "sereh": "lemongrass", "udang": "shrimp",
    "ayam": "chicken", "daging ayam": "chicken", "daging sapi": "beef",
    "daging kambing": "lamb", "ikan": "fish", "cumi": "squid",
    "bawang goreng": "shallot", "tempe": "tempeh", "tahu": "tofu",
    "kentang": "potato", "cengkeh": "clove", "kayu manis": "cinnamon",
    "pala": "nutmeg", "jinten": "cumin", "kapulaga": "cardamom",
    "santan": "coconut_milk", "kelapa": "coconut", "kelapa parut": "coconut",
    "terasi": "shrimp_paste", "asam jawa": "tamarind", "asam": "tamarind",
    "mentega": "butter", "margarin": "margarine", "susu": "milk",
    "susu kental manis": "condensed_milk", "keju": "cheese",
    "nasi": "rice", "beras": "rice", "mie": "noodle", "bihun": "vermicelli",
    "kol": "cabbage", "sawi": "bok_choy", "kangkung": "water_spinach",
    "bayam": "spinach", "buncis": "green_bean", "kacang panjang": "green_bean",
    "kacang tanah": "peanut", "kacang hijau": "mung_bean",
    "kacang merah": "kidney_bean", "toge": "bean_sprout", "tauge": "bean_sprout",
    "jagung": "corn", "labu": "pumpkin", "terong": "eggplant",
    "timun": "cucumber", "jamur": "mushroom", "pisang": "banana",
    "nanas": "pineapple", "mangga": "mango", "alpukat": "avocado",
    "saus sambal": "chili_sauce", "sambal": "chili_sauce",
    "saus tomat": "tomato", "cuka": "vinegar", "madu": "honey",
    "vanili": "vanilla", "cokelat": "chocolate", "coklat": "chocolate",
    "ragi": "yeast", "baking powder": "baking_powder", "soda kue": "baking_soda",
    "daun kemangi": "basil", "kemangi": "basil", "daun pandan": "pandan_leaf",
    "kunyit bubuk": "turmeric", "bumbu": "spice_mix", "kaldu ayam": "chicken_broth",
    "minyak zaitun": "olive_oil", "roti": "bread", "tepung panir": "bread_crumbs",
    "krim": "cream", "yogurt": "yogurt", "es batu": "ice",
}

# ----------------------------------------------------------------- German
DE = {
    "salz": "salt", "pfeffer": "black_pepper", "salz und pfeffer": "salt",
    "zwiebel": "onion", "zwiebeln": "onion", "butter": "butter",
    "ei": "egg", "eier": "egg", "eigelb": "egg_yolk", "eiweiss": "egg_white",
    "eiweiß": "egg_white", "öl": "oil", "olivenöl": "olive_oil",
    "mehl": "flour", "knoblauch": "garlic", "knoblauchzehe": "garlic",
    "knoblauchzehen": "garlic", "zucker": "sugar", "puderzucker": "sugar",
    "brauner zucker": "brown_sugar", "sahne": "cream",
    "schlagsahne": "cream", "saure sahne": "sour_cream",
    "crème fraîche": "creme_fraiche", "petersilie": "parsley",
    "kartoffel": "potato", "kartoffeln": "potato", "muskat": "nutmeg",
    "muskatnuss": "nutmeg", "zitronensaft": "lemon", "zitrone": "lemon",
    "möhre": "carrot", "möhren": "carrot", "karotte": "carrot",
    "karotten": "carrot", "gemüsebrühe": "vegetable_stock",
    "fleischbrühe": "broth", "hühnerbrühe": "chicken_broth",
    "brühe": "broth", "milch": "milk", "tomatenmark": "tomato",
    "tomate": "tomato", "tomaten": "tomato", "wasser": "water",
    "paprikapulver": "paprika", "paprikaschote": "bell_pepper",
    "parmesan": "parmesan_cheese", "käse": "cheese", "frischkäse": "cream_cheese",
    "butterschmalz": "butter", "lorbeerblatt": "bay_leaf",
    "lorbeerblätter": "bay_leaf", "dill": "dill", "frühlingszwiebel": "scallion",
    "senf": "mustard", "thymian": "thyme", "champignons": "mushroom",
    "pilze": "mushroom", "schalotte": "shallot", "schalotten": "shallot",
    "sojasauce": "soy_sauce", "weisswein": "white_wine", "weißwein": "white_wine",
    "rotwein": "red_wine", "lauch": "leek", "porree": "leek",
    "basilikum": "basil", "hackfleisch": "beef", "rinderhack": "beef",
    "zucchini": "zucchini", "cayennepfeffer": "cayenne_pepper",
    "schnittlauch": "chive", "kümmel": "caraway_seed", "semmelbrösel": "bread_crumbs",
    "paniermehl": "bread_crumbs", "currypulver": "curry_powder",
    "majoran": "marjoram", "rosmarin": "rosemary", "honig": "honey",
    "speisestärke": "cornstarch", "stärke": "cornstarch", "essig": "vinegar",
    "balsamico": "balsamic_vinegar", "backpulver": "baking_powder",
    "natron": "baking_soda", "hefe": "yeast", "vanillezucker": "vanilla",
    "vanille": "vanilla", "zimt": "cinnamon", "nelken": "clove",
    "ingwer": "ginger", "oregano": "oregano", "salbei": "sage",
    "hähnchen": "chicken", "hähnchenbrust": "chicken",
    "huhn": "chicken", "rindfleisch": "beef", "schweinefleisch": "pork",
    "speck": "bacon", "schinken": "ham", "wurst": "sausage",
    "lachs": "salmon", "thunfisch": "tuna", "garnelen": "shrimp",
    "fisch": "fish", "reis": "rice", "nudeln": "pasta",
    "spaghetti": "pasta", "brot": "bread", "toast": "bread",
    "blätterteig": "puff_pastry", "hefeteig": "dough", "quark": "quark",
    "joghurt": "yogurt", "mozzarella": "mozzarella_cheese",
    "gouda": "gouda_cheese", "feta": "feta_cheese", "schafskäse": "feta_cheese",
    "spinat": "spinach", "brokkoli": "broccoli", "blumenkohl": "cauliflower",
    "kohl": "cabbage", "weisskohl": "cabbage", "rosenkohl": "brussels_sprout",
    "sellerie": "celery", "gurke": "cucumber", "erbsen": "pea",
    "bohnen": "bean", "linsen": "lentil", "kichererbsen": "chickpea",
    "mais": "corn", "aubergine": "eggplant", "kürbis": "pumpkin",
    "rote bete": "beet", "apfel": "apple", "äpfel": "apple",
    "banane": "banana", "orange": "orange", "erdbeeren": "strawberry",
    "himbeeren": "raspberry", "blaubeeren": "blueberry", "kirschen": "cherry",
    "birne": "pear", "pfirsich": "peach", "rosinen": "raisin",
    "walnüsse": "walnut", "mandeln": "almond", "haselnüsse": "hazelnut",
    "kokosraspeln": "coconut", "schokolade": "chocolate", "kakao": "cocoa_powder",
    "marzipan": "marzipan", "marmelade": "jam", "ahornsirup": "maple_syrup",
    "gelatine": "gelatin", "grieß": "semolina", "haferflocken": "oat",
    "rum": "rum", "bier": "beer", "sonnenblumenöl": "sunflower_oil",
    "rapsöl": "canola_oil", "margarine": "margarine", "kondensmilch": "condensed_milk",
}

# ------------------------------------------------------------------ Greek
EL = {
    "αλάτι": "salt", "πιπέρι": "black_pepper", "ελαιόλαδο": "olive_oil",
    "λάδι": "oil", "κρεμμύδια": "onion", "κρεμμύδι": "onion",
    "ξερά κρεμμύδια": "onion", "σκόρδο": "garlic", "σκόρδου": "garlic",
    "σκελίδες": "garlic", "αλεύρι": "flour", "ζάχαρη": "sugar",
    "αυγά": "egg", "αυγό": "egg", "βούτυρο": "butter", "γάλα": "milk",
    "νερό": "water", "ντομάτες": "tomato", "ντοματάκια": "tomato",
    "ντομάτα": "tomato", "πατάτες": "potato", "πατάτα": "potato",
    "καρότα": "carrot", "καρότο": "carrot", "μαϊντανός": "parsley",
    "μαϊντανό": "parsley", "άνηθος": "dill", "άνηθο": "dill",
    "ρίγανη": "oregano", "βασιλικός": "basil", "θυμάρι": "thyme",
    "δεντρολίβανο": "rosemary", "δάφνη": "bay_leaf", "κανέλα": "cinnamon",
    "μοσχοκάρυδο": "nutmeg", "γαρίφαλο": "clove", "κύμινο": "cumin",
    "πάπρικα": "paprika", "λεμόνι": "lemon", "λεμόνια": "lemon",
    "χυμό λεμονιού": "lemon", "χυμός λεμονιού": "lemon",
    "πορτοκάλι": "orange", "πορτοκάλια": "orange", "ρύζι": "rice",
    "ζυμαρικά": "pasta", "μακαρόνια": "pasta", "κιμάς": "beef",
    "κιμά": "beef", "μοσχάρι": "beef", "χοιρινό": "pork",
    "κοτόπουλο": "chicken", "αρνί": "lamb", "ψάρι": "fish",
    "γαρίδες": "shrimp", "καλαμάρια": "squid", "χταπόδι": "octopus",
    "φέτα": "feta_cheese", "τυρί": "cheese", "κεφαλοτύρι": "cheese",
    "παρμεζάνα": "parmesan_cheese", "γιαούρτι": "yogurt",
    "κρέμα γάλακτος": "cream", "μαγιά": "yeast", "μπέικιν πάουντερ": "baking_powder",
    "σόδα": "baking_soda", "βανίλια": "vanilla", "κακάο": "cocoa_powder",
    "σοκολάτα": "chocolate", "κουβερτούρα": "chocolate",
    "μέλι": "honey", "καρύδια": "walnut", "αμύγδαλα": "almond",
    "φιστίκια": "pistachio", "σταφίδες": "raisin", "ελιές": "olive",
    "σπανάκι": "spinach", "μελιτζάνες": "eggplant", "κολοκυθάκια": "zucchini",
    "πιπεριές": "bell_pepper", "πιπεριά": "bell_pepper", "αγγούρι": "cucumber",
    "μαρούλι": "lettuce", "λάχανο": "cabbage", "μανιτάρια": "mushroom",
    "φασόλια": "bean", "φακές": "lentil", "ρεβίθια": "chickpea",
    "αρακάς": "pea", "μπρόκολο": "broccoli", "κουνουπίδι": "cauliflower",
    "πράσο": "leek", "σέλινο": "celery", "χόρτα": "salad_greens",
    "φύλλο κρούστας": "phyllo_dough", "ταχίνι": "tahini", "ξίδι": "vinegar",
    "ξύδι": "vinegar", "κρασί": "wine", "λευκό κρασί": "white_wine",
    "κόκκινο κρασί": "red_wine", "ούζο": "ouzo", "γιαούρτι στραγγιστό": "yogurt",
    "ψωμί": "bread", "φρυγανιά": "bread_crumbs", "σιμιγδάλι": "semolina",
    "κορν φλάουρ": "cornstarch", "μήλα": "apple", "μπανάνες": "banana",
    "φράουλες": "strawberry", "σοκολάτα γάλακτος": "milk_chocolate",
    "μαργαρίνη": "margarine", "μουστάρδα": "mustard", "μαγιονέζα": "mayonnaise",
}

# ---------------------------------------------------------------- Persian
FA = {
    "نمک": "salt", "فلفل": "black_pepper", "فلفل سیاه": "black_pepper",
    "پیاز": "onion", "سیر": "garlic", "روغن": "oil",
    "روغن زیتون": "olive_oil", "آرد": "flour", "شکر": "sugar",
    "تخم مرغ": "egg", "کره": "butter", "شیر": "milk", "آب": "water",
    "گوجه فرنگی": "tomato", "رب گوجه فرنگی": "tomato",
    "سیب زمینی": "potato", "هویج": "carrot", "جعفری": "parsley",
    "شوید": "dill", "نعناع": "mint", "گشنیز": "coriander",
    "زردچوبه": "turmeric", "دارچین": "cinnamon", "زعفران": "saffron",
    "زیره": "cumin", "هل": "cardamom", "برنج": "rice",
    "گوشت": "meat", "گوشت چرخ کرده": "beef", "مرغ": "chicken",
    "ماهی": "fish", "میگو": "shrimp", "پنیر": "cheese",
    "ماست": "yogurt", "خامه": "cream", "لیمو": "lemon",
    "آب لیمو": "lemon", "آبلیمو": "lemon", "سرکه": "vinegar",
    "عسل": "honey", "گردو": "walnut", "بادام": "almond",
    "پسته": "pistachio", "کشمش": "raisin", "خرما": "date",
    "نخود": "chickpea", "لوبیا": "bean", "عدس": "lentil",
    "بادمجان": "eggplant", "کدو": "zucchini", "اسفناج": "spinach",
    "کاهو": "lettuce", "خیار": "cucumber", "کلم": "cabbage",
    "قارچ": "mushroom", "فلفل دلمه ای": "bell_pepper", "لپه": "pea",
    "زرشک": "barberry", "آلو": "plum", "سیب": "apple",
    "موز": "banana", "پرتقال": "orange", "توت فرنگی": "strawberry",
    "شکر قهوه ای": "brown_sugar", "وانیل": "vanilla",
    "بکینگ پودر": "baking_powder", "جوش شیرین": "baking_soda",
    "مایه خمیر": "yeast", "کاکائو": "cocoa_powder", "شکلات": "chocolate",
    "نان": "bread", "ماکارونی": "pasta", "سبزی": "herb",
    "ریحان": "basil", "آویشن": "thyme", "سماق": "sumac",
    "گلاب": "rosewater", "کره بادام زمینی": "peanut_butter",
    "شیره انگور": "molasses", "تخم مرغ": "egg", "آب مرغ": "chicken_broth",
    "روغن مایع": "vegetable_oil", "پودر قند": "sugar",
}

# ----------------------------------------------------------------- Hebrew
HE = {
    "מלח": "salt", "פלפל": "black_pepper", "פלפל שחור": "black_pepper",
    "בצל": "onion", "שום": "garlic", "שמן": "oil",
    "שמן זית": "olive_oil", "קמח": "flour", "סוכר": "sugar",
    "ביצים": "egg", "ביצה": "egg", "חמאה": "butter", "חלב": "milk",
    "מים": "water", "עגבניות": "tomato", "רסק עגבניות": "tomato",
    "תפוחי אדמה": "potato", "גזר": "carrot", "פטרוזיליה": "parsley",
    "שמיר": "dill", "נענע": "mint", "כוסברה": "coriander",
    "כורכום": "turmeric", "קינמון": "cinnamon", "כמון": "cumin",
    "פפריקה": "paprika", "אורז": "rice", "בשר": "meat",
    "בשר טחון": "beef", "עוף": "chicken", "חזה עוף": "chicken",
    "דג": "fish", "סלמון": "salmon", "גבינה": "cheese",
    "גבינה צהובה": "cheese", "גבינת שמנת": "cream_cheese",
    "יוגורט": "yogurt", "שמנת": "cream", "שמנת מתוקה": "cream",
    "לימון": "lemon", "מיץ לימון": "lemon", "חומץ": "vinegar",
    "דבש": "honey", "אגוזים": "walnut", "שקדים": "almond",
    "צימוקים": "raisin", "תמרים": "date", "חומוס": "chickpea",
    "שעועית": "bean", "עדשים": "lentil", "חציל": "eggplant",
    "קישוא": "zucchini", "תרד": "spinach", "חסה": "lettuce",
    "מלפפון": "cucumber", "כרוב": "cabbage", "פטריות": "mushroom",
    "פלפל אדום": "red_pepper", "תפוח": "apple", "בננה": "banana",
    "תפוז": "orange", "תותים": "strawberry", "אבוקדו": "avocado",
    "סוכר חום": "brown_sugar", "וניל": "vanilla",
    "אבקת אפייה": "baking_powder", "סודה לשתייה": "baking_soda",
    "שמרים": "yeast", "קקאו": "cocoa_powder", "שוקולד": "chocolate",
    "לחם": "bread", "פירורי לחם": "bread_crumbs", "פסטה": "pasta",
    "טחינה": "tahini", "סילאן": "date", "זעתר": "zaatar",
    "חרדל": "mustard", "מיונז": "mayonnaise", "קטשופ": "ketchup",
    "רוטב סויה": "soy_sauce", "שמן קנולה": "canola_oil",
    "קמח תופח": "flour", "סולת": "semolina", "שיבולת שועל": "oat",
}

# --------------------------------------------------------------- Japanese
JA = {
    "塩": "salt", "こしょう": "black_pepper", "胡椒": "black_pepper",
    "砂糖": "sugar", "醤油": "soy_sauce", "しょうゆ": "soy_sauce",
    "みりん": "mirin", "酒": "sake", "日本酒": "sake", "酢": "vinegar",
    "米酢": "rice_vinegar", "味噌": "miso", "みそ": "miso",
    "だし": "dashi", "だし汁": "dashi", "水": "water",
    "油": "oil", "サラダ油": "vegetable_oil", "ごま油": "sesame_oil",
    "オリーブオイル": "olive_oil", "バター": "butter", "卵": "egg",
    "たまご": "egg", "牛乳": "milk", "小麦粉": "flour",
    "薄力粉": "flour", "強力粉": "flour", "片栗粉": "starch",
    "パン粉": "bread_crumbs", "玉ねぎ": "onion", "たまねぎ": "onion",
    "にんにく": "garlic", "ニンニク": "garlic", "しょうが": "ginger",
    "生姜": "ginger", "長ねぎ": "scallion", "ねぎ": "scallion",
    "にんじん": "carrot", "人参": "carrot", "じゃがいも": "potato",
    "トマト": "tomato", "キャベツ": "cabbage", "白菜": "napa_cabbage",
    "きゅうり": "cucumber", "なす": "eggplant", "大根": "daikon",
    "ほうれん草": "spinach", "もやし": "bean_sprout", "ピーマン": "bell_pepper",
    "きのこ": "mushroom", "しいたけ": "shiitake_mushroom",
    "えのき": "enoki_mushroom", "しめじ": "mushroom",
    "豆腐": "tofu", "納豆": "natto", "油揚げ": "fried_tofu_puff",
    "鶏肉": "chicken", "鶏むね肉": "chicken", "鶏もも肉": "chicken",
    "豚肉": "pork", "豚バラ肉": "pork", "牛肉": "beef",
    "ひき肉": "meat", "ベーコン": "bacon", "ハム": "ham",
    "ソーセージ": "sausage", "рыба": "fish", "魚": "fish",
    "鮭": "salmon", "まぐろ": "tuna", "えび": "shrimp",
    "いか": "squid", "あさり": "clam", "海苔": "nori",
    "わかめ": "wakame", "昆布": "kombu", "かつお節": "bonito_flakes",
    "ご飯": "rice", "米": "rice", "パスタ": "pasta", "うどん": "udon_noodle",
    "そば": "noodle", "ラーメン": "ramen_noodle", "паста": "pasta",
    "チーズ": "cheese", "生クリーム": "cream",
    "マヨネーズ": "mayonnaise", "ケチャップ": "ketchup",
    "ソース": "brown_sauce", "オイスターソース": "oyster_sauce",
    "はちみつ": "honey", "レモン": "lemon", "レモン汁": "lemon",
    "ごま": "sesame_seed", "白ごま": "sesame_seed", "コンソメ": "broth",
    "カレー粉": "curry_powder", "唐辛子": "chili_pepper",
    "七味唐辛子": "chili_powder", "わさび": "wasabi", "からし": "mustard",
    "ベーキングパウダー": "baking_powder", "バニラエッセンス": "vanilla",
    "ココア": "cocoa_powder", "チョコレート": "chocolate",
    "粉砂糖": "sugar", "きび砂糖": "brown_sugar",
    "りんご": "apple", "バナナ": "banana", "いちご": "strawberry",
    "かぼちゃ": "pumpkin", "とうもろこし": "corn", "枝豆": "edamame",
    "ヨーグルト": "yogurt", "コーンスターチ": "cornstarch",
}

# ------------------------------------------------------------------- Thai
TH = {
    "เกลือ": "salt", "พริกไทย": "black_pepper", "น้ำตาล": "sugar",
    "น้ำตาลทราย": "sugar", "น้ำตาลปี๊บ": "palm_sugar",
    "น้ำปลา": "fish_sauce", "ซีอิ๊วขาว": "soy_sauce", "ซอสหอยนางรม": "oyster_sauce",
    "น้ำมัน": "oil", "น้ำมันพืช": "vegetable_oil", "น้ำมันหอย": "oyster_sauce",
    "กระเทียม": "garlic", "หอมแดง": "shallot", "หอมใหญ่": "onion",
    "พริก": "chili_pepper", "พริกขี้หนู": "chili_pepper",
    "พริกแห้ง": "chili_pepper", "ตะไคร้": "lemongrass", "ข่า": "galangal",
    "ใบมะกรูด": "kaffir_lime_leaf", "ขมิ้น": "turmeric", "ขิง": "ginger",
    "ผักชี": "coriander", "โหระพา": "basil", "กะเพรา": "thai_basil",
    "มะนาว": "lime", "น้ำมะนาว": "lime", "มะเขือเทศ": "tomato",
    "มะเขือ": "eggplant", "แตงกวา": "cucumber", "แครอท": "carrot",
    "มันฝรั่ง": "potato", "กะหล่ำปลี": "cabbage", "ถั่วงอก": "bean_sprout",
    "ถั่วฝักยาว": "green_bean", "ถั่วลิสง": "peanut", "เห็ด": "mushroom",
    "ข้าว": "rice", "ข้าวสวย": "rice", "แป้ง": "flour",
    "แป้งข้าวเจ้า": "rice", "แป้งมัน": "tapioca",
    "กะทิ": "coconut_milk", "มะพร้าว": "coconut", "ไข่": "egg",
    "ไข่ไก่": "egg", "นม": "milk", "เนย": "butter", "ชีส": "cheese",
    "หมู": "pork", "หมูสับ": "pork", "เนื้อ": "beef",
    "ไก่": "chicken", "อกไก่": "chicken", "กุ้ง": "shrimp",
    "ปลา": "fish", "ปลาหมึก": "squid", "ปู": "crab",
    "เต้าหู้": "tofu", "เส้นก๋วยเตี๋ยว": "rice_noodle", "วุ้นเส้น": "glass_noodle",
    "บะหมี่": "noodle", "น้ำ": "water", "น้ำเปล่า": "water",
    "ซอสมะเขือเทศ": "tomato", "ซอสพริก": "chili_sauce",
    "พริกป่น": "chili_powder", "ผงกะหรี่": "curry_powder",
    "พริกแกง": "curry_paste", "กะปิ": "shrimp_paste",
    "น้ำส้มสายชู": "vinegar", "งา": "sesame_seed", "ผงฟู": "baking_powder",
    "วานิลลา": "vanilla", "ผงโกโก้": "cocoa_powder",
    "ช็อกโกแลต": "chocolate", "น้ำผึ้ง": "honey", "ต้นหอม": "scallion",
    "ผักกาด": "lettuce", "ฟักทอง": "pumpkin", "ข้าวโพด": "corn",
    "สับปะรด": "pineapple", "กล้วย": "banana", "มะม่วง": "mango",
}

# --------------------------------------------------------------- Filipino
FIL = {
    "asin": "salt", "paminta": "black_pepper", "asukal": "sugar",
    "bawang": "garlic", "sibuyas": "onion", "mantika": "oil",
    "langis": "oil", "mantikilya": "butter", "harina": "flour",
    "itlog": "egg", "gatas": "milk", "tubig": "water",
    "kamatis": "tomato", "patatas": "potato", "karot": "carrot",
    "toyo": "soy_sauce", "suka": "vinegar", "patis": "fish_sauce",
    "bagoong": "shrimp_paste", "gata": "coconut_milk", "niyog": "coconut",
    "luya": "ginger", "sili": "chili_pepper", "dahon ng laurel": "bay_leaf",
    "manok": "chicken", "baboy": "pork", "baka": "beef",
    "isda": "fish", "hipon": "shrimp", "kanin": "rice",
    "bigas": "rice", "malagkit": "glutinous_rice", "pancit": "noodle",
    "repolyo": "cabbage", "petsay": "bok_choy", "kangkong": "water_spinach",
    "talong": "eggplant", "kalabasa": "pumpkin", "sitaw": "green_bean",
    "okra": "okra", "mais": "corn", "saging": "banana",
    "mangga": "mango", "keso": "cheese", "kalamansi": "calamansi",
    "asukal na pula": "brown_sugar", "gata ng niyog": "coconut_milk",
    "tanglad": "lemongrass", "pinya": "pineapple", "ubas": "grape",
    "monggo": "mung_bean", "tokwa": "tofu", "kamote": "sweet_potato",
    "ampalaya": "bitter_melon", "labanos": "radish", "gabi": "taro",
    "hibe": "dried_shrimp", "tinapa": "cured_fish", "atsuete": "annatto_seed",
}

# --------------------------------------------------------------- Romanian
RO = {
    "sare": "salt", "piper": "black_pepper", "zahar": "sugar",
    "zahăr": "sugar", "usturoi": "garlic", "ceapa": "onion",
    "ceapă": "onion", "ulei": "oil", "ulei de masline": "olive_oil",
    "unt": "butter", "faina": "flour", "făină": "flour",
    "oua": "egg", "ouă": "egg", "ou": "egg", "lapte": "milk",
    "apa": "water", "apă": "water", "rosii": "tomato", "roșii": "tomato",
    "bulion": "tomato", "cartofi": "potato", "morcov": "carrot",
    "morcovi": "carrot", "patrunjel": "parsley", "pătrunjel": "parsley",
    "marar": "dill", "mărar": "dill", "cimbru": "thyme",
    "foi de dafin": "bay_leaf", "boia": "paprika", "smantana": "sour_cream",
    "smântână": "sour_cream", "branza": "cheese", "brânză": "cheese",
    "cascaval": "cheese", "cașcaval": "cheese", "iaurt": "yogurt",
    "orez": "rice", "carne": "meat", "carne tocata": "beef",
    "pui": "chicken", "piept de pui": "chicken", "porc": "pork",
    "vita": "beef", "peste": "fish", "pește": "fish",
    "ardei": "bell_pepper", "ardei gras": "bell_pepper", "castraveti": "cucumber",
    "varza": "cabbage", "varză": "cabbage", "spanac": "spinach",
    "ciuperci": "mushroom", "vinete": "eggplant", "dovlecel": "zucchini",
    "fasole": "bean", "mazare": "pea", "porumb": "corn",
    "lamaie": "lemon", "lămâie": "lemon", "otet": "vinegar",
    "oțet": "vinegar", "miere": "honey", "nuci": "walnut",
    "stafide": "raisin", "mere": "apple", "banane": "banana",
    "capsuni": "strawberry", "vanilie": "vanilla",
    "praf de copt": "baking_powder", "bicarbonat": "baking_soda",
    "drojdie": "yeast", "cacao": "cocoa_powder", "ciocolata": "chocolate",
    "paine": "bread", "pesmet": "bread_crumbs", "gris": "semolina",
    "paste": "pasta", "vin": "wine", "smochine": "fig",
}

LEXICONS = {"tr": TR, "es": ES, "vi": VI, "id": ID, "de": DE, "el": EL,
            "fa": FA, "he": HE, "ja": JA, "th": TH, "fil": FIL, "ro": RO}

# Languages with no word boundaries -- substring matching, not \b regex.
NO_BOUNDARY = {"ja", "th", "zh"}


def validate(vocab: dict) -> dict[str, list[str]]:
    """Return, per language, the lexicon targets that aren't real vocab terms.

    A typo'd target is the worst kind of bug here: it neither raises nor shows
    up in match-rate totals, it just quietly discards that ingredient forever.
    """
    bad = {}
    for lang, m in LEXICONS.items():
        miss = sorted({v for v in m.values() if v not in vocab})
        if miss:
            bad[lang] = miss
    return bad
