#!/usr/bin/env python3
"""Parse the epicure-explorer Gradio API docs into a structured reference.

Input is the raw text of https://kaikaku-epicure-explorer.hf.space/?view=api
(saved verbatim to data/raw/epicure-explorer/gradio_api_docs.txt).

Emits docs/EXPLORER_API_REFERENCE.md with every endpoint, its parameters,
types, defaults, UI labels and return values. Giant Literal[...] enumerations
(the 1,790-ingredient vocabulary) are collapsed -- they're in vocab.json.
"""
from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "data" / "raw" / "epicure-explorer" / "gradio_api_docs.txt"
OUT = ROOT / "docs" / "EXPLORER_API_REFERENCE.md"
JSON_OUT = ROOT / "data" / "derived" / "explorer_api.json"

MAX_LITERAL = 140


def squash(t: str) -> str:
    """Collapse the 1,790-item ingredient enums to something readable."""
    t = " ".join(t.split())
    for m in sorted(re.findall(r"Literal\[[^\]]*\]", t), key=len, reverse=True):
        if len(m) > MAX_LITERAL:
            n = m.count(",") + 1
            head = ", ".join(m[8:-1].split(", ")[:3])
            t = t.replace(m, f"Literal[{head}, ... ({n} values)]")
    return t.strip()


def parse(raw: str) -> list[dict]:
    blocks = re.split(r"^api_name: (/\S+)\s*$", raw, flags=re.M)
    eps = []
    for name, body in zip(blocks[1::2], blocks[2::2]):
        ep = {"api_name": name, "params": [], "returns": []}

        call = re.search(r"result = client\.predict\((.*?)\n\)", body, re.S)
        if call:
            args = []
            for line in call.group(1).splitlines():
                line = line.strip().rstrip(",")
                if not line or line.startswith("api_name="):
                    continue
                args.append(squash(line))
            ep["signature"] = args

        n_par = re.search(r"Accepts (\d+) parameters?:", body)
        ep["n_params"] = int(n_par.group(1)) if n_par else 0
        n_ret = re.search(r"Returns (\d+) elements?", body)
        ep["n_returns"] = int(n_ret.group(1)) if n_ret else 0

        # split into the parameter region and the return region
        par_txt, ret_txt = body, ""
        if n_ret:
            i = body.index(n_ret.group(0))
            par_txt, ret_txt = body[:i], body[i:]
        if n_par:
            par_txt = par_txt[par_txt.index(n_par.group(0)) + len(n_par.group(0)):]

        for chunk in re.finditer(
                r"^(\w+)\s+(.*?)\s*$\n+\s*The input value that is provided in the "
                r'"(.*?)" (\w+) component\.', par_txt, re.M | re.S):
            nm, typ, label, comp = chunk.groups()
            default = None
            d = re.search(r"\s*Default:\s*(.*)$", typ)
            if d:
                default = d.group(1).strip()
                typ = typ[:d.start()]
            ep["params"].append({"name": nm, "type": squash(typ),
                                 "default": default, "label": label,
                                 "component": comp})

        for chunk in re.finditer(
                r"^(.*?)\s*$\n+\s*The output value that appears in the "
                r'"(.*?)" (\w+) component\.', ret_txt, re.M | re.S):
            typ, label, comp = chunk.groups()
            typ = re.sub(r"^Returns \d+ elements?\s*", "", typ.strip())
            ep["returns"].append({"type": squash(typ), "label": label,
                                  "component": comp})
        eps.append(ep)
    return eps


def is_programmatic(e: dict) -> bool:
    """True for endpoints declared with gr.api() rather than wired to a UI event.

    Gradio names UI-bound arguments after their component label ("Ingredient
    basket"); pure API endpoints have no component, so they fall back to
    positional placeholders (parameter_217). That placeholder is the tell.
    """
    return bool(e["params"]) and all(
        re.fullmatch(r"(parameter|value)_\d+", p["label"]) for p in e["params"])


def render(eps: list[dict]) -> str:
    L = ["# epicure-explorer — full API reference", "",
         "Auto-generated by `tools/parse_api_docs.py` from",
         "`data/raw/epicure-explorer/gradio_api_docs.txt`",
         "(captured from <https://kaikaku-epicure-explorer.hf.space/?view=api>).", "",
         "See `docs/EXPLORER_API.md` for what this API is useful for — in short, it is a",
         "**bit-exact conformance oracle** for the Swift port (100% parity over 54 calls),",
         "but it does **not** reproduce the paper's published tables.", "",
         "## Calling it without the `gradio_client` dependency", "",
         "Two steps: POST to get an `event_id`, then GET the SSE stream.", "",
         "```bash", 'BASE=https://kaikaku-epicure-explorer.hf.space/gradio_api/call',
         'EID=$(curl -s -X POST "$BASE/neighbors" -H "Content-Type: application/json" \\',
         '  -d \'{"data":["miso","core",5]}\' | sed -n \'s/.*"event_id":"\\([^"]*\\)".*/\\1/p\')',
         'curl -s "$BASE/neighbors/$EID"',
         "# event: complete",
         '# data: [[{"name":"mirin","cosine":0.788707}, ...]]', "```", "",
         "`tools/api_differential.py` implements this with retries and an on-disk cache.", "",
         "## ⚠️ Only 4 of these 34 endpoints are a real API", "",
         "Gradio exposes *every* event handler as an endpoint, so the list below",
         "conflates two very different things:", "",
         "- **4 programmatic endpoints** (`gr.api(...)`) — `/neighbors`, `/slerp`,",
         "  `/arithmetic`, `/embed`. Clean JSON in, clean JSON out. These are a",
         "  deliberate contract and are what `tools/api_differential.py` targets.",
         "- **30 UI event handlers** — incidental exposure of the Gradio UI wiring.",
         "  They return rendered HTML or plot payloads, their arguments are ordered",
         "  by widget layout, and they will break on any UI edit. Do not depend on them.", "",
         "The tell: a real API endpoint has no UI component, so Gradio falls back to",
         "positional placeholder labels (`parameter_217`). A UI handler carries the",
         'human label ("Ingredient basket"). `is_programmatic()` uses exactly this.', "",
         "**Arguments are positional over raw HTTP.** The `data` array must follow the",
         "parameter order in the tables below — e.g. `/slerp` is",
         "`[seed, direction, theta_deg, sibling, k]`, with `sibling` *after* `theta_deg`.",
         "That ordering is empirically confirmed: it is what produced 100% parity.", "",
         f"## Endpoint index ({len(eps)})", "",
         "| endpoint | params | returns | purpose |", "|---|---|---|---|"]
    for e in eps:
        star = " ⭐" if is_programmatic(e) else ""
        purpose = e["params"][0]["label"] if e["params"] else (
            e["returns"][0]["label"] if e["returns"] else "—")
        L.append(f"| `{e['api_name']}`{star} | {e['n_params']} | {e['n_returns']} | {purpose} |")
    L += ["", "⭐ = stable programmatic endpoint. Unstarred rows are UI event handlers.",
          "", "---", "", "## Endpoints", ""]
    for e in eps:
        L.append(f"### `{e['api_name']}`")
        if e.get("signature"):
            L += ["", "```python", 'client = Client("Kaikaku/epicure-explorer")',
                  "result = client.predict(", *[f"    {a}," for a in e["signature"]],
                  f'    api_name="{e["api_name"]}"', ")", "```", ""]
        if e["params"]:
            L += [f"**Parameters ({e['n_params']})**", "",
                  "| name | type | default | UI label | component |", "|---|---|---|---|---|"]
            for p in e["params"]:
                L.append(f"| `{p['name']}` | `{p['type']}` | "
                         f"{'`'+p['default']+'`' if p['default'] else '—'} | "
                         f"{p['label']} | {p['component']} |")
            L.append("")
        if e["returns"]:
            L += [f"**Returns ({e['n_returns']})**", "",
                  "| type | UI label | component |", "|---|---|---|"]
            for r in e["returns"]:
                L.append(f"| `{r['type']}` | {r['label']} | {r['component']} |")
            L.append("")
    return "\n".join(L) + "\n"


if __name__ == "__main__":
    eps = parse(SRC.read_text(errors="replace"))
    OUT.write_text(render(eps))
    JSON_OUT.write_text(json.dumps(eps, indent=1))
    tot_p = sum(e["n_params"] for e in eps)
    miss = [e["api_name"] for e in eps if e["n_params"] != len(e["params"])]
    print(f"parsed {len(eps)} endpoints, {tot_p} declared parameters, "
          f"{sum(len(e['params']) for e in eps)} extracted")
    if miss:
        print(f"  partial extraction on {len(miss)}: {', '.join(miss[:8])}")
    print(f"wrote {OUT.relative_to(ROOT)} and {JSON_OUT.relative_to(ROOT)}")
